name: mnist_numbers
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11.5
  - pytorch
  - numpy
  - pyyaml
  - tqdm
  - tabulate
  - psutil
  - matplotlib
  # also, krakenex, install with pip (not in conda)
  # also coremltools, install with pip (ancient version only in conda)
  # also, plotext, install with pip (not in conda)

# after updates:
# conda env update --file environment.yml
